param(
  [string]$InputWav = "Samples\static_tuner\gc.wav",
  [string]$OutputHeader = "Core\Inc\static_tuner_real_sample.h",
  [double]$StartSecond = 6.0,
  [int]$OutputSampleRate = 16000,
  [int]$FrameLength = 4096,
  [string]$SourceUrl = "https://raw.githubusercontent.com/pdx-cs-sound/wavs/main/gc.wav",
  [string]$License = "CC0, from pdx-cs-sound/wavs README"
)

function Read-U16Le($Bytes, $Offset) {
  return [BitConverter]::ToUInt16($Bytes, $Offset)
}

function Read-U32Le($Bytes, $Offset) {
  return [BitConverter]::ToUInt32($Bytes, $Offset)
}

$wavPath = Resolve-Path $InputWav
$bytes = [IO.File]::ReadAllBytes($wavPath)

if ([Text.Encoding]::ASCII.GetString($bytes, 0, 4) -ne "RIFF" -or
    [Text.Encoding]::ASCII.GetString($bytes, 8, 4) -ne "WAVE") {
  throw "Input is not a RIFF/WAVE file: $wavPath"
}

$offset = 12
$formatTag = $null
$channels = $null
$sampleRate = $null
$bitsPerSample = $null
$dataOffset = $null
$dataSize = $null

while ($offset + 8 -le $bytes.Length) {
  $chunkId = [Text.Encoding]::ASCII.GetString($bytes, $offset, 4)
  $chunkSize = Read-U32Le $bytes ($offset + 4)
  $chunkData = $offset + 8

  if ($chunkId -eq "fmt ") {
    $formatTag = Read-U16Le $bytes $chunkData
    $channels = Read-U16Le $bytes ($chunkData + 2)
    $sampleRate = Read-U32Le $bytes ($chunkData + 4)
    $bitsPerSample = Read-U16Le $bytes ($chunkData + 14)
  }
  elseif ($chunkId -eq "data") {
    $dataOffset = $chunkData
    $dataSize = $chunkSize
    break
  }

  $offset = $chunkData + $chunkSize
  if (($offset % 2) -ne 0) {
    $offset++
  }
}

if ($formatTag -ne 1 -or $bitsPerSample -ne 16) {
  throw "Only PCM 16-bit WAV files are supported. format=$formatTag bits=$bitsPerSample"
}

if ($channels -lt 1) {
  throw "Invalid channel count: $channels"
}

if ($sampleRate % $OutputSampleRate -ne 0) {
  throw "This converter expects an integer downsample ratio. input=$sampleRate output=$OutputSampleRate"
}

$bytesPerFrame = 2 * $channels
$inputFrames = [int]($dataSize / $bytesPerFrame)
$ratio = [int]($sampleRate / $OutputSampleRate)
$startInputFrame = [int][Math]::Round($StartSecond * $sampleRate)
$availableOutputFrames = [int](($inputFrames - $startInputFrame) / $ratio)

if ($startInputFrame -lt 0 -or $availableOutputFrames -lt $FrameLength) {
  throw "Not enough WAV data from StartSecond=$StartSecond for $FrameLength output samples"
}

$samples = New-Object int[] $FrameLength
$sumAbs = 0L
$min = 32767
$max = -32768
$checksum = 2166136261L

for ($i = 0; $i -lt $FrameLength; $i++) {
  $frame = $startInputFrame + ($i * $ratio)
  $sampleOffset = $dataOffset + ($frame * $bytesPerFrame)
  $sum = 0

  for ($ch = 0; $ch -lt $channels; $ch++) {
    $raw = [BitConverter]::ToInt16($bytes, $sampleOffset + (2 * $ch))
    $sum += $raw
  }

  $sample = [int][Math]::Round($sum / $channels)
  $samples[$i] = $sample

  if ($sample -lt $min) { $min = $sample }
  if ($sample -gt $max) { $max = $sample }
  $sumAbs += [Math]::Abs($sample)

  $u16 = $sample -band 0xFFFF
  $checksum = (($checksum -bxor ($u16 -band 0xFF)) * 16777619L) -band 0xFFFFFFFFL
  $checksum = (($checksum -bxor (($u16 -shr 8) -band 0xFF)) * 16777619L) -band 0xFFFFFFFFL
}

$sourceHash = (Get-FileHash -Algorithm SHA256 -Path $wavPath).Hash
$avgAbs = [int]($sumAbs / $FrameLength)
$sourceFile = Split-Path -Leaf $wavPath
$generatedUtc = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$outPath = Join-Path (Get-Location) $OutputHeader

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("#ifndef STATIC_TUNER_REAL_SAMPLE_H")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_H")
$lines.Add("")
$lines.Add("#include <stdint.h>")
$lines.Add("")
$lines.Add("/* Generated by Tools/convert_wav_to_static_tuner_sample.ps1. */")
$lines.Add("/* Source WAV: $sourceFile */")
$lines.Add("/* Source URL: $SourceUrl */")
$lines.Add("/* Source SHA256: $sourceHash */")
$lines.Add("/* License: $License */")
$lines.Add("/* Generated UTC: $generatedUtc */")
$lines.Add("")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_COUNT ${FrameLength}U")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_RATE_HZ ${OutputSampleRate}U")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_ORIGINAL_RATE_HZ ${sampleRate}U")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_ORIGINAL_CHANNELS ${channels}U")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_START_INPUT_FRAME ${startInputFrame}U")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_START_OUTPUT_FRAME $([int]($startInputFrame / $ratio))U")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_MIN ${min}")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_MAX ${max}")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_AVG_ABS ${avgAbs}U")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_CHECKSUM 0x$($checksum.ToString('X8'))U")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_SOURCE_FILE ""$sourceFile""")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_SOURCE_URL ""$SourceUrl""")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_SOURCE_SHA256 ""$sourceHash""")
$lines.Add("#define STATIC_TUNER_REAL_SAMPLE_LICENSE ""$License""")
$lines.Add("")
$lines.Add("static const int16_t staticTunerRealSample[STATIC_TUNER_REAL_SAMPLE_COUNT] = {")

for ($i = 0; $i -lt $FrameLength; $i += 8) {
  $chunk = @()
  for ($j = 0; $j -lt 8 -and ($i + $j) -lt $FrameLength; $j++) {
    $chunk += $samples[$i + $j].ToString()
  }
  $lines.Add("  " + ($chunk -join ", ") + ",")
}

$lines.Add("};")
$lines.Add("")
$lines.Add("#endif /* STATIC_TUNER_REAL_SAMPLE_H */")

New-Item -ItemType Directory -Force -Path (Split-Path $outPath) | Out-Null
[IO.File]::WriteAllLines($outPath, $lines)

[pscustomobject]@{
  output = $outPath
  source = $wavPath.Path
  sha256 = $sourceHash
  start_second = $StartSecond
  output_samples = $FrameLength
  checksum = ("0x{0:X8}" -f $checksum)
  min = $min
  max = $max
  avg_abs = $avgAbs
}
